apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowlatesttag
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowLatestTag
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisallowlatesttag

        violation[{"msg": msg, "details": {"container": container.name}}] {
          container := input.review.object.spec.containers[_]
          is_latest_tag(container.image)
          msg := sprintf("Container <%v> is using the 'latest' tag, which is disallowed.", [container.name])
        }

        violation[{"msg": msg, "details": {"initContainer": container.name}}] {
          container := input.review.object.spec.initContainers[_]
          is_latest_tag(container.image)
          msg := sprintf("InitContainer <%v> is using the 'latest' tag, which is disallowed.", [container.name])
        }

        is_latest_tag(image) {
          endswith(image, ":latest")
        }


