name: Multi-Cloud CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/static-website:latest
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE ./src
          docker push $DOCKER_IMAGE

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [eks, aks]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        if: matrix.cluster == 'eks'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Azure Login
        if: matrix.cluster == 'aks'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Cluster
        run: bash config/deploy.sh ${{ matrix.cluster }}

  policy-enforcement:
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [eks, aks]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        if: matrix.cluster == 'eks'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Azure Login
        if: matrix.cluster == 'aks'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure kubeconfig
        run: |
          if [ "${{ matrix.cluster }}" == "eks" ]; then
            aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
          else
            az aks get-credentials --resource-group $AZURE_RESOURCE_GROUP --name $AKS_CLUSTER_NAME
          fi

      - name: Install OPA Gatekeeper
        run: |
          kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.11/deploy/gatekeeper.yaml
          kubectl wait --for=condition=Available --timeout=180s -n gatekeeper-system deployment/gatekeeper-controller-manager

      - name: Apply ConstraintTemplate
        run: |
          kubectl apply -f policies/gatekeeper-templates/constraint-template.yaml

      - name: Wait for CRD to be Registered
        run: |
          for i in {1..10}; do
            if kubectl get crd k8sdisallowlatesttags.constraints.gatekeeper.sh; then
              echo "CRD found."
              break
            fi
            echo "Waiting for CRD k8sdisallowlatesttags to be created..."
            sleep 10
          done

      - name: Wait for CRD to be Established
        run: |
          kubectl wait --for=condition=Established --timeout=60s crd/k8sdisallowlatesttags.constraints.gatekeeper.sh

      - name: Re-Apply ConstraintTemplate
        run: |
          kubectl apply -f policies/gatekeeper-templates/constraint-template.yaml

      - name: Apply Constraint
        run: |
          kubectl apply -f policies/gatekeeper-templates/constraint.yaml

      - name: Verify Constraint
        run: |
          kubectl get k8sdisallowlatesttag
